name: flutter_quizme
description: "A new Flutter project"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  http: ^1.3.0
  flutter_spinkit: ^5.2.1
  animated_text_kit: ^4.2.2
  lottie: ^3.3.1
  shared_preferences: ^2.4.0
  connectivity_plus: ^6.1.2
  audioplayers: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path_android: "assets/images/play_store_512.png"
  image_path_ios: "assets/images/AppIcon@3x.png"
  adaptive_icon_background: "assets/images/ic_launcher_background.png"
  adaptive_icon_foreground: "assets/images/ic_launcher_foreground.png"
  adaptive_icon_monochrome: "assets/images/ic_launcher_monochrome.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/AppIcon@3x.png"

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/animations/
    - assets/sounds/



  fonts:
    - family: SfUi
      fonts:
        - asset: assets/font/SFUIDisplayRegular.otf
          weight: 400
        - asset: assets/font/SFUIDisplayBold.otf
          weight: 700
        - asset: assets/font/SFUIDisplayLight.otf
          weight: 300
        - asset: assets/font/SFUIDisplayMedium.otf
          weight: 500
        - asset: assets/font/SFUIDisplayHeavy.otf
          weight: 900
        - asset: assets/font/SFUIDisplaySemibold.otf
          weight: 600
